### ISSUE TITLE
Can we use it with history data from Google Maps?

### ISSUE THREAD

**Issue by adrienjoly** [sebastianvirlan/maps-journey-replay#1]
Hi! I found your project thanks to https://javascriptweekly.com.

I was wondering if it was possible to use it with history data from Google Maps? (i.e. the list of places where you went everyday, thanks to the location tracking, if it was enabled on your smartphone)

If so, do you have any advice on how to export that data and make your project work with it?

Thanks! :-)

**Comment by sebastianvirlan** [comment]
Hi @adrienjoly ,
I just analysed what data is Google Maps Timeline providing and you need:

1. Download the JSON with all the locations that Google Maps Timeline is providing.
2. Use dataMap to map (I just committed the implementation, see README) the data in the required format:

```javascript
fetchMapPoints: {
    url: window.location.origin + '/demo/timeline.json',
    dataMap: function (data) {
        var locations = data.locations.map(function(val) {
            return {
                lat: val.latitudeE7 * (10 ** -7),
                lng: val.longitudeE7 * (10 ** -7),
                timestamp: parseInt(val.timestampMs)
            }
        }).sort(function(a, b) { return a.timestamp - b.timestamp })

        return locations
    }
}
```
I improved the logs as well, so if you enable them or use the example provided in README it might be very helpful as sometimes the marker doesn't move if the data is not in the correct format / order.

If your issue is sorted let me know so I can close the issue.

**Comment by adrienjoly** [comment]
That looks pretty awesome, thanks for sharing this, Sebastian!

I'll give it a try when I have some spare time. Probably this weekend! ^^

**Comment by adrienjoly** [comment]
Just so you know, I wrote and published a `jq` script to select a date/time range from my 152 MB location history from Google: https://gist.github.com/adrienjoly/21e60637d536fdb790a34198449c377d

Now going to test your program! :-)

**Comment by adrienjoly** [comment]
FYI, here's how a part of a trip exported from Google Maps/Timeline looks like at `speed=5`:

![usa 5 (speed 5)](https://user-images.githubusercontent.com/531781/54085819-7157e900-4342-11e9-878b-a736c7c918b5.gif)
